//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliza
    {
        public int IDPoliza { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IDTipoCubrimiento { get; set; }
        public Nullable<double> Cobertura { get; set; }
        public Nullable<System.DateTime> InicioVigenciaPoliza { get; set; }
        public Nullable<int> PeriodoDeCobertura { get; set; }
        public Nullable<double> PrecioPoliza { get; set; }
        public Nullable<int> IDTipoRiesgo { get; set; }
        public Nullable<int> IDCliente { get; set; }
    }
}
